logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
tests:
  users:
    normal:
      username: normal_user
      password: password
    admin:
      username: admin_user
      password: password

